package net.runelite.client.plugins.microbot.zerozero.farmrun.enums;

public enum FarmRunState {
    RESET,
    RUNNING,
    FARMING_VARROCK,
    FARMING_FALADOR,
    FARMING_LUMBRIDGE,
    FARMING_TAVERLEY,
    FARMING_CATHERBY,
    FARMING_GNOME_VILLAGE,
    FARMING_GNOME_STRONGHOLD_FRUIT,
    FARMING_GNOME_STRONGHOLD,
    FARMING_GUILD_NORMAL,
    FARMING_GUILD_FRUIT,
    BANKING,
    FINISHED
}
